/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TestSwapAdapterInterface extends Interface {
    getFunction(nameOrSignature: "fundLiquidity" | "liquidity" | "owner" | "quote" | "setRate" | "swap"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Swap"): EventFragment;

    encodeFunctionData(functionFragment: 'fundLiquidity', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'liquidity', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'quote', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setRate', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swap', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'fundLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swap', data: BytesLike): Result;
  }

  
    export namespace SwapEvent {
      export type InputTuple = [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, amountOut: BigNumberish, sender: AddressLike];
      export type OutputTuple = [tokenIn: string, tokenOut: string, amountIn: bigint, amountOut: bigint, sender: string];
      export interface OutputObject {tokenIn: string, tokenOut: string, amountIn: bigint, amountOut: bigint, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TestSwapAdapter extends BaseContract {
    
    connect(runner?: ContractRunner | null): TestSwapAdapter;
    waitForDeployment(): Promise<this>;

    interface: TestSwapAdapterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    fundLiquidity: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    liquidity: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    quote: TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    setRate: TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, rate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    swap: TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'fundLiquidity'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'liquidity'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'quote'): TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setRate'): TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, rate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swap'): TypedContractMethod<
      [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Swap'): TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;

    filters: {
      
      'Swap(address,address,uint256,uint256,address)': TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
      Swap: TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
    
    };
  }